package modelo;
// Generated 22 mar 2023 10:52:22 by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "Products", catalog = "salesdb")
public class Products implements java.io.Serializable {

	private Integer productId;
	private Serializable name;
	private BigDecimal price;
	private Set<Sales> saleses = new HashSet<Sales>(0);

	public Products() {
	}

	public Products(Serializable name) {
		this.name = name;
	}

	public Products(Serializable name, BigDecimal price, Set<Sales> saleses) {
		this.name = name;
		this.price = price;
		this.saleses = saleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ProductID", unique = true, nullable = false)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "Name", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "Price", scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<Sales> getSaleses() {
		return this.saleses;
	}

	public void setSaleses(Set<Sales> saleses) {
		this.saleses = saleses;
	}

}

